services:
  arduino-builder-co2ampel:
    build: .
    image: arduino-builder-co2ampel
    container_name: co2ampel-builder
    volumes:
      - type: bind
        source: ./CO2-Ampel_Plus
        target: /usr/src/app/CO2-Ampel_Plus
      - type: bind
        source: ./arduino-builder-config.yml
        target: /usr/src/app/arduino-builder-config.yml
    entrypoint: [ "/venv/bin/python", "arduino-cli-config.py", "--no-init" ]

  arduino-builder-co2ampel-format:
    image: mfreudenberg/arduino-builder:0.1.1
    container_name: co2ampel-builder-format
    user: ${USER}
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app/
    entrypoint: [ "clang-format" ]
    command: ${FORMAT_COMMAND}
