name: Build and attach assets to release

on:
  release:
    types: [published]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: make build
    - name: Upload Release Asset bin
      id: upload-release-asset-bin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./build/CO2-Ampel_Plus.ino.bin
        asset_name: CO2-Ampel_Plus.ino.bin
        asset_content_type: application/octet-stream
    - name: Upload Release Asset elf
      id: upload-release-asset-elf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./build/CO2-Ampel_Plus.ino.elf
        asset_name: CO2-Ampel_Plus.ino.elf
        asset_content_type: application/octet-stream
    - name: Upload Release Asset hex
      id: upload-release-asset-hex
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./build/CO2-Ampel_Plus.ino.hex
        asset_name: CO2-Ampel_Plus.ino.hex
        asset_content_type: application/text